console.log("Módulo 03, Cápsula 01")
console.log("Arreglos (Arrays)")
console.log("\n")
console.log("Pero, ¿qué es un areglo")
console.log("Es una lista de valores encerrados entre corchetes y separados por comas")
console.log("Permiten el almacenamiento de datos en una misma variable")
console.log("Puede contener más de un valor al mismo tiempo")
console.log("Cada uno de estos valores se llaman Elementos")
console.log("\n")
console.log("¿Cómo se estructura un Array?")
console.log("\n")
const people=["Agapito","Melcacho","Galarga"]
console.log("¿Cómo se accede a los elementos de un Array?")
console.log(people)
console.log(people[1])
console.log("\n")
console.log("¿Cómo saber cuántos elementos componen un Array?")
people.length
console.log(people.length)
console.log("\n")
console.log("¿Cómo acceder al último elemento?")
people.length-1
console.log(people[people.length-1])
console.log("\n")