/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 5
  CÁPSULA 7. "FORMULARIOS"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* EJERCICIO 1: 
  EN ESTE ÚLTIMO EJERCICIO, GENERA UN FORMULARIO QUE INCLUYA 10 CAMPOS. EN CADA CAMPO ESTABLECE DIFERENTES TIPO DE RESPUESTAS:
  A) TEXTOS
  B) CHECKBOX
  C) SELECTED INDEX

  CAPTURA LOS DATOS A TRAVÉS DE SUBMIT Y EXPRÉSALOS DIRECTAMENTE EN UN ÁREA DE EJERCICIOS.HTML
*/
