/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 2
  CÁPSULA 6. "COLABORACIÓN CON FUNCIONES"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* 
  EJERCICIO 1: 
  CREA UNA FUNCIÓN "CARRO" QUE EJECUTE COMO COMO CONSTRUCTOR DE OBJETOS. PERMITE QUE PUEDA GENERARSE DOS PROPIEDADES UTILIZANDO THIS. POSTERIORMENTE, DECLARA UN MÉTODO.
*/



//==================================//
/* EJERCICIO 2: 
  DE LA FUNCIÓN ANTERIOR CREADA, GENERA UNA INSTANCIA Y REVISA SUS DOS PROPIEDADES ANCLADAS CON CONSOLE.LOG()
*/


//==================================//
/* EJERCICIO 3:
  DE LA INSTANCIA ANTERIOR CREADA, REVISA QUE LA FUNCIONALIDAD DEL MÉTODO CREADO EXISTA Y GENERA UN CONSOLE.LOG PARA COMPROBARLO.
*/

