/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 5
  CÁPSULA 5. "EVENTOS II"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* 
  EJERCICIO 1: 
  CREA DOS CAMPOS DE TEXTO. UNO QUE SE REFIERA A "NOMBRE" Y EL OTRO "APELLIDO". EN "EJERCICIOS.HTML". ADICIONALMENTE, UNA ETIQUETA PARA UN BOTÓN QUE DIGA "CREAR NOMBRE COMPLETO" Y UN ESPACIO "DIV" ESPECÍFICO PARA MOSTRAR EL NOMBRE.
  
  DENTRO DE EJERCICIOS.JS, ANCLA AMBOS VALORES A DOS VARIABLES RESPECTIVAMENTE Y PERMITE QUE SE CONCATENEN (JUNTEN) PARA FORMAR UN NOMBRE COMPLETO Y QUE SE EXPRESE EN EL "DIV" ESPECÍFICO, TAL COMO LO HICIMOS EN LA CÁPSULA.
*/


