console.log("Módulo 03")
console.log("Arreglos")
console.log("Cápsula 02")
console.log("Manipulación")
console.log("\n")
console.log("Manipulación de arreglos")
const people=["Rosa Celeste","Teorino Laraya","Elsa Pito"]
console.log(people)
console.log("\n")
console.log("¿Cómo sacar un elemento del arreglo (pop)")
console.log("Sacando el último elemento del arreglo")
people.pop()
console.log(people)
console.log("\n")
console.log("Quitar el primer elemento del arreglo (shifting)")
people.shift()
console.log(people)
console.log("\n")
console.log("Agregar nuevo elemento al arreglo, en la posición final")
people.push("Aitor Menta")
console.log(people)
console.log("\n")
console.log("Agregar nuevo elemento al arreglo, en la posición inicial (unshift)")
people.unshift("Laura Terrazco")
console.log(people)
console.log("\n")
console.log("Cambiar un elemento por otro en la posición elegida")
people[0]="Débora Teste"
console.log(people)
console.log("\n")
console.log("Cambiar de posición a uno o más elementos, quitando el primero, obteniendo así un nuevo arreglo, ya que original no sufre cambios. Slicing")
const newPeople=people.slice(1,3)
console.log(newPeople)
console.log(people)
console.log("\n")
console.log("Sustituir un elemento por otro. Splicing")
console.log(people)
people.splice(1,1,"Rosa Celeste")
console.log(people)
console.log("\n")
console.log("Sustituir dos elementos. Splicing")
console.log(people)
people.splice(1,2,"Rosa Celeste")
console.log(people)
console.log("\n")
console.log("Agregar un elemento. Splicing")
console.log(people)
people.splice(1,0,"Marisa Caleche")
console.log(people)