console.log("Módulo 03")
console.log("Cápsula 02")
console.log("Manipulación de Arreglos")
console.log("\n")
console.log("Ejercicio 01")
console.log("Crear un arreglo con 5 elementos. Cada uno de ellos con un tipo de dato distinto.")
console.log("\n")
const dataType=[500,"Aitor Menta", true, null, undefined]
console.log(dataType)
console.log("Posteriormente, eliminar el último elemento.")
console.log("\n")
dataType.pop()
console.log(dataType)
console.log("\n")
console.log("Ejercicio 02")
console.log("Agrega un elemento usando Push")
console.log("\n")
dataType.push("Laura Terrazco")
console.log(dataType)
console.log("\n")
console.log("Ejercicio 03")
console.log("Elimina el primer elemento mediant Shift")
console.log("\n")
dataType.shift()
console.log(dataType)
console.log("\n")
console.log("Ejercicio 04")
console.log("Agrega un elemento en la primera posición con Unshift")
console.log("\n")
dataType.unshift("Débora Teste")
console.log(dataType)
