/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 2
  CÁPSULA 4. "MANIPULACIÓN DE PROPIEDADES"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* EJERCICIO 1: 
  CREA UN OBJETO "RESTAURANTE" Y GENERA 2 PROPIEDADES.
  A) TIPODECOMIDA (STRING)
  B) UBICACION (STRING)
*/






//================= =================//
/* EJERCICIO 2: 
  DEL OBJETO ANTERIOR, AGREGA UNA NUEVA PROPIEDAD LLAMADA "NOMBRE" CON UN TIPO DE DATO STRING A TRAVÉS DE "DOT NOTATION". 
  POSTERIORMENTE AGREGA UNA PROPIEDAD NUEVA LLAMADA "SERVICIO A DOMICILIO" CON UN TIPO DE DATO BOOLEANO, UTILIZANDO LA MISMA TÉCNICA. 
  FINALMENTE, MODIFICA EL VALOR DE UBICACIÓN UTILIZANDO "DOT NOTATION"
*/
  

