/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 2
  CÁPSULA 5. "MÉTODOS DE OBJETO"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* 
  EJERCICIO 1: CREA 3 OBJETOS LITERALES CON DIFERENTES PROPIEDADES EN CADA UNO.
  POSTERIORMENTE, EJECUTA OBJECT ASSIGN PARA CREAR UN NUEVO OBJETO COMBINANDO LAS PROPIEDADES DE TODOS LOS OBJETOS LITERALES.
*/


//================= =================//
/* 
  EJERCICIO 2: 
  CREA 3 OBJETOS LITERALES CON PROPIEDADES IGUALES EN CADA UNO.
  POSTERIORMENTE, EJECUTA OBJECT ASSIGN PARA CREAR UN NUEVO OBJETO QUE INCLUYA ESTAS PROPIEDADES.
*/



