/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 5
  CÁPSULA 4. "EVENTOS"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* 
  EJERCICIO 1: 
  OBSERVA TU ARCHIVO EJERCICIOS.HTML E IDENTIFICA LA ETIQUETA "BUTTON" CON EL ID "CREAR".
  POSTERIORMENTE, GENERA UNA VARIABLE PARA IDENTIFICARLO DENTRO DE ESTE ARCHIVO DE JS CON QUERYSELECTOR.

  UNA VEZ HECHO ESTO, GENERA UNA VARIABLE PARA IDENTIFICAR LA ETIQUETA "DIV" CON EL ID "RESULTADO" A TRAVÉS DE QUERYSELECTOR.
*/



//================= =================//
/* EJERCICIO 2: 
  CREA UN EVENTO CON ADDEVENTLISTENER, EL CUAL, AL DARLE CLICK AL BOTÓN DE "CREAR", 
  GENERE UNA ETIQUETA "P" DENTRO DE LA SECCIÓN DE ID "RESULTADO", CON UN TEXTO LIBRE.

*/
